#!/bin/bash

### Run functions
function deploy-test() {
    # Network for deployment
    NETWORK=$1

    # Attach into docker
    docker exec -i -t truffle_container /bin/bash -c "
        cd ../ && ./scripts/deploy-test.sh ${NETWORK}
    "
}

function deploy() {    
    # Network for deployment
    NETWORK=$1

    # Attach into docker
    docker exec -i -t truffle_container /bin/bash -c "
        cd ../ && ./scripts/deploy.sh ${NETWORK}
    "
}

function test() {
    #Network 
    NETWORK=$1

    # Attach into docker
    docker exec -i -t truffle_container /bin/bash -c "
        cd ../ && ./scripts/test.sh ${NETWORK}
    "
}

### Create Functions
function private-create-contract() {
    #Contract
    CONTRACTNAME=$1

    # Attach into docker
    docker exec -i -t truffle_container /bin/bash -c "
        cd ../ && ./scripts/create-contract.sh ${CONTRACTNAME}
    "
}

function create-migration() {
    #Contract
    CONTRACTNAME=$1

    # Attach into docker
    docker exec -i -t truffle_container /bin/bash -c "
        cd ../ && ./scripts/create-migration.sh ${CONTRACTNAME}
    "
}

function create-test() {
    # Name of contract
    CONTRACTNAME=$1

    # Attach into docker
    docker exec -i -t truffle_container /bin/bash -c "
        cd ../ && ./scripts/create-test.sh ${CONTRACTNAME}
    "
}

function create-contract() {
    #Contract
    CONTRACTNAME=$1

    # Attach into docker
    docker exec -i -t truffle_container /bin/bash -c "
        cd ../ && ./scripts/create-contract.sh ${CONTRACTNAME}
        ./scripts/create-migration.sh ${CONTRACTNAME}
        ./scripts/create-test.sh ${CONTRACTNAME}
    "
}

cmd="$1"
shift
eval "$cmd $@"